# Generated by Django 5.1.3 on 2024-11-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='farmerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmerName', models.CharField(max_length=50)),
                ('industryName', models.CharField(max_length=50)),
                ('materialType', models.CharField(max_length=50)),
                ('quantityAvailable', models.IntegerField()),
                ('phoneNumber', models.PositiveBigIntegerField()),
                ('upiID', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='industryrequirement',
            name='industryName',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
