# Generated by Django 5.1.3 on 2024-11-21 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_farmerrequest_priceoffered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industryrequirement',
            name='industryName',
            field=models.CharField(max_length=50),
        ),
    ]
