# Generated by Django 5.1.3 on 2024-11-22 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_industryrequirement_industryname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industryrequirement',
            name='industryName',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
