# Generated by Django 5.1.3 on 2024-11-22 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_industryrequirement_industryname'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='industryrequirement',
            unique_together={('industryName', 'materialType')},
        ),
    ]
