# Generated by Django 5.1.3 on 2024-12-06 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_farmerrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industryrequirement',
            name='industryName',
            field=models.CharField(max_length=50),
        ),
    ]
