# Generated by Django 5.1.3 on 2024-12-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_industryrequirement_industryname'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedbacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userType', models.CharField(max_length=15)),
                ('feedback', models.CharField(max_length=1000)),
            ],
        ),
    ]
